/**
 * WealthPlanrAI — Compliance Module
 * ==========================================================================
 * Centralized compliance scaffolding. Single source of truth for:
 *   - Disclaimer text constants (website, intake, PDFs, AI outputs)
 *   - Marketing language guardrails (allowed vs disallowed terms)
 *   - AI output sanitizer (rejects imperative/prescriptive language)
 *   - Audit trail schema and helpers
 *   - Intake consent gate definition
 *   - PDF watermark constants
 *
 * IMPORTANT: This module enforces WealthPlanrAI's positioning as an
 * EDUCATION + INTAKE + ADVISOR ENABLEMENT platform. It is NOT an
 * investment adviser, broker-dealer, insurance producer, or mortgage lender.
 * Every output that reaches a user must pass through these guardrails.
 *
 * Last updated: 2026-05
 * ==========================================================================
 */

// ============================================================================
// SECTION 1 — DISCLAIMER TEXT CONSTANTS
// ============================================================================

export const DISCLAIMER_VERSION = '2026.05.01';

/**
 * Master disclaimer block — used as the canonical reference text.
 * All other disclaimer surfaces are summarized versions of this.
 */
export const MASTER_DISCLAIMER = `
WealthPlanrAI provides financial education, planning tools, and informational
resources designed to help individuals better understand their financial
situation and prepare for conversations with qualified professionals.

WealthPlanrAI does not provide investment advice, financial planning advice,
legal advice, tax advice, mortgage advice, insurance advice, accounting advice,
or any other professional advisory services.

Use of this platform does not create an advisor-client, fiduciary, CFP®,
attorney-client, CPA-client, broker-client, mortgage originator-client, or
insurance producer-client relationship.

WealthPlanrAI does not recommend specific securities, investments, insurance
products, loans, mortgages, refinancing decisions, or financial transactions.

All reports, summaries, projections, and AI-generated insights are provided
for educational and informational purposes only and should not be relied upon
as individualized professional advice.

Users should consult with a licensed Certified Financial Planner (CFP®),
Registered Investment Adviser (RIA), CPA, attorney, mortgage professional,
insurance professional, or other qualified advisor before making financial
decisions.

We do not guarantee financial outcomes, investment returns, tax savings, loan
approval, mortgage rates, insurance eligibility, or any specific financial
results.
`.trim();

/** Compact disclaimer — for footers, email, app badges. */
export const FOOTER_DISCLAIMER =
  'Educational platform only. Not financial advice. Not an investment ' +
  'adviser, broker-dealer, or insurance producer. Use of this platform ' +
  'does not create an advisor-client relationship. Consult a licensed ' +
  'professional before making financial decisions.';

/** PDF watermark — printed on every page header. */
export const PDF_WATERMARK_HEADER = 'EDUCATIONAL SUMMARY ONLY — NOT FINANCIAL ADVICE';

/** PDF page footer block. */
export const PDF_FOOTER_DISCLAIMER =
  'This report is provided for educational and informational purposes only ' +
  'and does not constitute financial, investment, tax, legal, mortgage, ' +
  'insurance, or accounting advice. Please consult a qualified licensed ' +
  'professional before making financial decisions. WealthPlanrAI is not ' +
  'liable for decisions made based on this report.';

/** AI output disclaimer — appended to any AI-generated text section. */
export const AI_OUTPUT_DISCLAIMER =
  'AI-generated summaries may be incomplete, inaccurate, or based on ' +
  'assumptions provided by the user. These outputs are intended only to ' +
  'support financial education and planning preparation and should not be ' +
  'treated as professional advice or recommendations. Final financial ' +
  'decisions should be reviewed with a qualified licensed professional.';

/** Advisor-PDF specific disclaimer — appears on the advisor intake report. */
export const ADVISOR_PDF_DISCLAIMER =
  'This intake intelligence report is generated by WealthPlanrAI from ' +
  'client-provided data and standardized planning frameworks (including the ' +
  'NASAA Series 65 suitability framework). Specific products and strategies ' +
  'named in this report represent FRAMEWORK ALIGNMENT only and are NOT ' +
  'recommendations from WealthPlanrAI. The licensed advisor receiving this ' +
  'report is solely responsible for: (a) suitability determinations, (b) ' +
  'fiduciary obligations, (c) regulatory compliance and licensing, (d) ' +
  'supervision and disclosure obligations, and (e) all client recommendations. ' +
  'WealthPlanrAI is not an investment adviser, broker-dealer, insurance ' +
  'producer, or mortgage lender, and assumes no liability for advisor ' +
  'recommendations or client outcomes.';

/** Client-PDF specific disclaimer — appears on the client educational summary. */
export const CLIENT_PDF_DISCLAIMER =
  'This educational summary is generated by WealthPlanrAI to help you ' +
  'understand your financial situation and prepare for a conversation with a ' +
  'licensed financial professional. It is NOT financial advice and does NOT ' +
  'recommend any specific investment, insurance product, loan, or financial ' +
  'transaction. The figures shown are educational reference points based on ' +
  'general planning frameworks and the data you provided. Your actual ' +
  'situation may differ in important ways that only a licensed advisor, CFP®, ' +
  'CPA, attorney, or other qualified professional can assess. WealthPlanrAI ' +
  'is not liable for any financial decisions made based on this summary.';

// ============================================================================
// SECTION 2 — INTAKE CONSENT GATE
// ============================================================================

export interface ConsentItem {
  key: string;
  text: string;
  required: boolean;
}

export const INTAKE_CONSENT_ITEMS: ConsentItem[] = [
  {
    key: 'educational_use_only',
    text: 'I understand that WealthPlanrAI is an educational platform and does not provide personalized financial advice.',
    required: true,
  },
  {
    key: 'no_advisor_relationship',
    text: 'I understand that no advisor-client, fiduciary, legal, tax, mortgage, insurance, or investment advisory relationship is created through use of this platform.',
    required: true,
  },
  {
    key: 'outputs_informational_only',
    text: 'I understand that any summaries, projections, assessments, or AI-generated outputs are for informational purposes only and are not recommendations.',
    required: true,
  },
  {
    key: 'will_consult_professional',
    text: 'I understand that I should consult with a licensed financial advisor, CFP®, CPA, attorney, mortgage professional, or insurance professional before making financial decisions.',
    required: true,
  },
  {
    key: 'data_use_consent',
    text: 'I consent to the collection and use of my financial information in accordance with the Privacy Policy and Terms of Service.',
    required: true,
  },
  {
    key: 'ai_use_disclosure',
    text: 'I understand that this platform uses AI to generate educational summaries, and that AI outputs may be incomplete, inaccurate, or outdated.',
    required: true,
  },
];

// ============================================================================
// SECTION 3 — ADVISOR PLATFORM AGREEMENT
// ============================================================================

export const ADVISOR_AGREEMENT_ITEMS: ConsentItem[] = [
  {
    key: 'advisor_licensing_responsibility',
    text: 'I confirm that I hold all required licenses for the advice and services I provide, and that I am solely responsible for maintaining those licenses.',
    required: true,
  },
  {
    key: 'advisor_compliance_responsibility',
    text: 'I am solely responsible for regulatory compliance, including but not limited to SEC, FINRA, NASAA, state insurance, and state securities requirements.',
    required: true,
  },
  {
    key: 'advisor_fiduciary_responsibility',
    text: 'I acknowledge that any fiduciary, suitability, or best-interest obligations to clients are mine alone — WealthPlanrAI does not assume these obligations.',
    required: true,
  },
  {
    key: 'advisor_supervision_responsibility',
    text: 'I am responsible for supervising any recommendations I make, and for ensuring my recommendations are appropriate for each client.',
    required: true,
  },
  {
    key: 'platform_not_advisor',
    text: 'I acknowledge that WealthPlanrAI is an educational and intake-intelligence platform, NOT an investment adviser, broker-dealer, insurance producer, or mortgage lender, and that products named in WealthPlanrAI reports are framework-alignment references, not recommendations from WealthPlanrAI.',
    required: true,
  },
  {
    key: 'advisor_disclosure_responsibility',
    text: 'I am responsible for providing all required disclosures to clients (Form ADV, Form CRS, fee disclosures, conflict-of-interest disclosures, etc.).',
    required: true,
  },
  {
    key: 'advisor_indemnification',
    text: 'I agree to indemnify WealthPlanrAI against claims arising from my recommendations, advice, or interactions with clients.',
    required: true,
  },
];

// ============================================================================
// SECTION 4 — MARKETING LANGUAGE GUARDRAILS
// ============================================================================

/**
 * ALLOWED marketing terms — always safe to use.
 */
export const MARKETING_ALLOWED_TERMS = [
  'financial clarity',
  'planning preparation',
  'advisor readiness',
  'financial organization',
  'education-first',
  'financial wellness',
  'prepare for advisor conversations',
  'financial confidence',
  'better planning',
  'organize your finances',
  'understand your finances',
  'pre-advisor intelligence',
  'intake intelligence',
];

/**
 * DISALLOWED marketing terms — implicate advisory or guarantee territory.
 * Any UI/marketing copy containing these triggers should fail compliance review.
 */
export const MARKETING_DISALLOWED_TERMS = [
  'we improve your returns',
  'we optimize your investments',
  'guaranteed wealth',
  'guaranteed returns',
  'guaranteed retirement',
  'best investment',
  'best recommendations',
  'personalized financial advice',
  'personal financial advisor',
  'we recommend',
  'our recommendation',
  'guaranteed savings',
  'maximize your returns',
  'beat the market',
  'optimize returns',
];

/** Quick check used by linters / pre-publish hooks. */
export function checkMarketingCopy(copy: string): {
  passed: boolean;
  violations: string[];
} {
  const lower = copy.toLowerCase();
  const violations = MARKETING_DISALLOWED_TERMS.filter((t) => lower.includes(t));
  return { passed: violations.length === 0, violations };
}

// ============================================================================
// SECTION 5 — AI OUTPUT SANITIZER
// ============================================================================

/**
 * Imperative/prescriptive language that an AI must NOT produce in any
 * client-facing or advisor-facing output.
 *
 * The sanitizer scans free-text AI outputs for these patterns and either:
 *   - rewrites them educationally, or
 *   - rejects them and triggers regeneration.
 */
/**
 * Imperative/prescriptive language patterns. Each entry is either:
 *   - a static replacement (string), or
 *   - a function that receives match groups and returns the educational rewrite.
 */
const PRESCRIPTIVE_PHRASE_PATTERNS: Array<{
  pattern: RegExp;
  educationalReplacement: string | ((match: string, ...groups: string[]) => string);
}> = [
  // Direct imperatives
  { pattern: /\byou should (buy|invest in|sell|move|transfer|switch to|put your)\b/gi,
    educationalReplacement: 'a topic to discuss with your advisor is whether to' },
  { pattern: /\b(buy|sell) (this|that|the) (stock|fund|bond|security|annuity)\b/gi,
    educationalReplacement: (_m, action: string, _det: string, prod: string) =>
      `discuss the role of this ${prod} in your portfolio with your advisor`,
  },
  { pattern: /\bmove (your|the) (ira|401\(?k\)?|portfolio|funds?) (to|into)\b/gi,
    educationalReplacement: (_m, _det: string, acct: string, _prep: string) =>
      `consider discussing whether moving your ${acct} could fit your plan`,
  },
  { pattern: /\brefinance now\b/gi,
    educationalReplacement: 'consider discussing refinancing options with a mortgage professional' },
  { pattern: /\bwe recommend\b/gi,
    educationalReplacement: 'a planning topic to discuss is' },
  { pattern: /\bour recommendation is\b/gi,
    educationalReplacement: 'a framework-aligned topic for advisor discussion is' },
  // Guarantee language
  { pattern: /\b(guaranteed|guarantee) (returns?|growth|outcomes?|wealth|savings?)\b/gi,
    educationalReplacement: (_m, _g: string, what: string) =>
      `historical patterns of ${what} (no guarantees)`,
  },
  { pattern: /\bwill (definitely|certainly|surely) (earn|gain|grow|return)\b/gi,
    educationalReplacement: (_m, _adv: string, verb: string) =>
      `may ${verb} (educational projection only)`,
  },
  // Specific product imperatives
  { pattern: /\bbuy (apple|tesla|microsoft|google|amazon|nvidia|meta)\b/gi,
    educationalReplacement: 'discuss diversified equity exposure with your advisor' },
];

export interface SanitizeResult {
  sanitized: string;
  violationsFound: number;
  changes: Array<{ original: string; replacement: string }>;
  passed: boolean;
}

/**
 * Sanitize AI-generated text. Returns the cleaned text plus an audit log of changes.
 * Use BEFORE displaying any AI output to a user.
 */
export function sanitizeAiOutput(text: string): SanitizeResult {
  let result = text;
  const changes: Array<{ original: string; replacement: string }> = [];
  let totalViolations = 0;

  for (const { pattern, educationalReplacement } of PRESCRIPTIVE_PHRASE_PATTERNS) {
    const matches = Array.from(result.matchAll(pattern));
    if (matches.length === 0) continue;

    totalViolations += matches.length;
    if (typeof educationalReplacement === 'string') {
      for (const m of matches) {
        changes.push({ original: m[0], replacement: educationalReplacement });
      }
      result = result.replace(pattern, educationalReplacement);
    } else {
      const fn = educationalReplacement;
      result = result.replace(pattern, (...args) => {
        const matchText = String(args[0]);
        const groups = args.slice(1, -2).map((g) => String(g ?? ''));
        const replacement = fn(matchText, ...groups);
        changes.push({ original: matchText, replacement });
        return replacement;
      });
    }
  }

  return {
    sanitized: result,
    violationsFound: totalViolations,
    changes,
    passed: totalViolations === 0,
  };
}

/**
 * Strict mode: returns null if any violation is found, signaling the caller
 * to regenerate rather than display a sanitized version.
 */
export function sanitizeAiOutputStrict(text: string): string | null {
  const r = sanitizeAiOutput(text);
  if (!r.passed) return null;
  return r.sanitized;
}

// ============================================================================
// SECTION 6 — AUDIT TRAIL SCHEMA
// ============================================================================

export interface DisclosureAcknowledgment {
  disclosureKey: string;
  disclosureVersion: string;
  acknowledgedAt: string;        // ISO 8601 timestamp
  ipAddress?: string;
  userAgent?: string;
}

export interface AuditTrailEntry {
  assessmentId: string;
  userId?: string;
  advisorId?: string;
  consents: DisclosureAcknowledgment[];
  reportVersion: string;
  engineVersion: string;
  generatedAt: string;
  aiSanitizerInvocations: number;
  aiSanitizerViolationsBlocked: number;
  events: Array<{
    type: 'consent' | 'assessment_started' | 'assessment_completed'
        | 'report_generated' | 'pdf_downloaded' | 'email_sent'
        | 'advisor_assigned' | 'ai_output_blocked';
    at: string;
    metadata?: Record<string, unknown>;
  }>;
}

/** Constructs a fresh audit trail. Call at assessment start. */
export function newAuditTrail(args: {
  assessmentId: string;
  userId?: string;
  advisorId?: string;
}): AuditTrailEntry {
  return {
    assessmentId: args.assessmentId,
    userId: args.userId,
    advisorId: args.advisorId,
    consents: [],
    reportVersion: DISCLAIMER_VERSION,
    engineVersion: '2.0.0',
    generatedAt: new Date().toISOString(),
    aiSanitizerInvocations: 0,
    aiSanitizerViolationsBlocked: 0,
    events: [
      { type: 'assessment_started', at: new Date().toISOString() },
    ],
  };
}

/** Appends a consent acknowledgment. */
export function recordConsent(
  trail: AuditTrailEntry,
  disclosureKey: string,
  ctx?: { ipAddress?: string; userAgent?: string },
): void {
  const now = new Date().toISOString();
  trail.consents.push({
    disclosureKey,
    disclosureVersion: DISCLAIMER_VERSION,
    acknowledgedAt: now,
    ipAddress: ctx?.ipAddress,
    userAgent: ctx?.userAgent,
  });
  trail.events.push({
    type: 'consent',
    at: now,
    metadata: { disclosureKey, version: DISCLAIMER_VERSION },
  });
}

/** Records an audit trail event. */
export function recordEvent(
  trail: AuditTrailEntry,
  type: AuditTrailEntry['events'][number]['type'],
  metadata?: Record<string, unknown>,
): void {
  trail.events.push({
    type,
    at: new Date().toISOString(),
    metadata,
  });
}

/** Verifies that all required intake consents have been recorded. */
export function verifyIntakeConsentsComplete(trail: AuditTrailEntry): {
  complete: boolean;
  missing: string[];
} {
  const required = INTAKE_CONSENT_ITEMS.filter((c) => c.required).map((c) => c.key);
  const recorded = new Set(trail.consents.map((c) => c.disclosureKey));
  const missing = required.filter((k) => !recorded.has(k));
  return { complete: missing.length === 0, missing };
}

// ============================================================================
// SECTION 7 — DISCLAIMER ATTACHMENT HELPER
// ============================================================================

/**
 * Wraps any structured output with a disclaimer envelope.
 * All engine outputs that leave the server should be wrapped this way before
 * being sent to the client.
 */
export interface DisclaimerEnvelope<T> {
  disclaimerVersion: string;
  educationalNotice: string;
  notFinancialAdvice: true;
  noAdvisorRelationship: true;
  consultProfessional: string;
  payload: T;
}

export function wrapWithDisclaimer<T>(payload: T): DisclaimerEnvelope<T> {
  return {
    disclaimerVersion: DISCLAIMER_VERSION,
    educationalNotice:
      'This output is provided for educational and informational purposes only.',
    notFinancialAdvice: true,
    noAdvisorRelationship: true,
    consultProfessional:
      'Consult a licensed CFP®, RIA, CPA, attorney, or other qualified ' +
      'professional before making financial decisions.',
    payload,
  };
}
