-- WealthPlanrAI — Migration 011
-- Adds JSONB columns for the new Series 65 intake-analysis engine output.
-- Runs alongside legacy score_results column without breaking it.

alter table assessments
  add column if not exists intake_analysis jsonb,
  add column if not exists client_summary  jsonb,
  add column if not exists audit_trail     jsonb;

-- Consents — stores intake consent acknowledgments per assessment
alter table assessments
  add column if not exists intake_consents jsonb;

-- Advisor agreement — stores advisor signup compliance acknowledgments
alter table profiles
  add column if not exists advisor_agreement jsonb;

comment on column assessments.intake_analysis is
  'Series 65 framework analysis output (advisor view). Generated by analyzeIntake().';
comment on column assessments.client_summary is
  'Educational client-facing summary. Generated by translateForClient().';
comment on column assessments.audit_trail is
  'Audit trail of consents and events for this assessment.';
comment on column assessments.intake_consents is
  'Intake consent acknowledgments collected before assessment started.';
comment on column profiles.advisor_agreement is
  'Advisor agreement acknowledgments collected at signup.';
